// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCikD91dW1Wf19RB-heK_xspA9oQgqRQtg',
    appId: '1:873361647636:web:7b5267111ce87a9e0f9f01',
    messagingSenderId: '873361647636',
    projectId: 'online-booking-84498',
    authDomain: 'online-booking-84498.firebaseapp.com',
    storageBucket: 'online-booking-84498.firebasestorage.app',
    measurementId: 'G-BF4R18CLX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYF-O_9jRmQfQnVv3FMdDPhIsG2stR6k',
    appId: '1:873361647636:android:f7ef0ea3e3354b9a0f9f01',
    messagingSenderId: '873361647636',
    projectId: 'online-booking-84498',
    storageBucket: 'online-booking-84498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_kccJsQL-lZErLWsjIdmstlzeKwl-wU8',
    appId: '1:873361647636:ios:a6bc1f0ef39570460f9f01',
    messagingSenderId: '873361647636',
    projectId: 'online-booking-84498',
    storageBucket: 'online-booking-84498.firebasestorage.app',
    iosClientId: '873361647636-j1j6nqloibk3hruvn127sk5sdbuv31u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_kccJsQL-lZErLWsjIdmstlzeKwl-wU8',
    appId: '1:873361647636:ios:a6bc1f0ef39570460f9f01',
    messagingSenderId: '873361647636',
    projectId: 'online-booking-84498',
    storageBucket: 'online-booking-84498.firebasestorage.app',
    iosClientId: '873361647636-j1j6nqloibk3hruvn127sk5sdbuv31u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCikD91dW1Wf19RB-heK_xspA9oQgqRQtg',
    appId: '1:873361647636:web:4eee3e25b6a8f47d0f9f01',
    messagingSenderId: '873361647636',
    projectId: 'online-booking-84498',
    authDomain: 'online-booking-84498.firebaseapp.com',
    storageBucket: 'online-booking-84498.firebasestorage.app',
    measurementId: 'G-K84XJGW7L8',
  );
}
